In [10]:
import pandas as pd

geography_raw = pd.read_csv("geography.csv")
customers_raw = pd.read_csv("customers.csv")
product_epd_raw = pd.read_json("epd.json")
promotion_eprom_raw = pd.read_json("eprom.json")
shipments_realistic_raw = pd.read_csv("shipments_realistic.csv")
tf_raw = pd.read_json("tf.json")
web_traffic_raw = pd.read_csv("web_traffic.csv")

In [18]:

# GEOGRAPHY

geography = geography_raw[
    [
        "zip",
        "city",
        "region",
        "district"
    ]
].copy()

# Chuẩn hóa text
for col in [
    "city",
    "region",
    "district"
]:
    geography[col] = (
        geography[col]
        .astype("string")
        .str.strip()
    )

# Chuẩn hóa ZIP
geography["zip"] = pd.to_numeric(
    geography["zip"],
    errors="coerce"
).astype("Int64")

# Xóa ZIP bị thiếu
geography = geography.dropna(
    subset=["zip"]
)

# Xóa ZIP trùng
geography = geography.drop_duplicates(
    subset=["zip"]
).reset_index(drop=True)

# Kiểm tra
print("Geography:")
print(geography.info())
print("\nNull:")
print(geography.isnull().sum())
print("\nDuplicate zip:",
      geography["zip"].duplicated().sum())

geography.head()

Geography:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39948 entries, 0 to 39947
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   zip       39948 non-null  Int64
 1   city      39948 non-null  string
 2   region    39948 non-null  string
 3   district  39948 non-null  string
dtypes: Int64(1), string(3)
memory usage: 1.3 MB
None

Null:
zip         0
city        0
region      0
district    0
dtype: int64

Duplicate zip: 0

     zip       city region      district
0  15201  Hai Phong   East  District #13
1  15202     Phu Ly   East  District #13
2  15203   Viet Tri   East  District #13
3  15204  Bac Giang   East  District #13
4  15205  Bac Giang   East  District #13

In [17]:

# CUSTOMERS


customers = customers_raw[
    [
        "customer_id",
        "zip",
        "city",
        "signup_date",
        "gender",
        "age_group",
        "acquisition_channel"
    ]
].copy()

# Chuẩn hóa dữ liệu text
for col in [
    "city",
    "gender",
    "age_group",
    "acquisition_channel"
]:
    customers[col] = (
        customers[col]
        .astype("string")
        .str.strip()
    )

# Chuẩn hóa ID và ZIP
customers["customer_id"] = pd.to_numeric(
    customers["customer_id"],
    errors="coerce"
).astype("Int64")

customers["zip"] = pd.to_numeric(
    customers["zip"],
    errors="coerce"
).astype("Int64")

# Chuẩn hóa ngày
customers["signup_date"] = pd.to_datetime(
    customers["signup_date"],
    errors="coerce"
)

# Xóa customer không có ID
customers = customers.dropna(
    subset=["customer_id"]
)

# Xóa customer bị trùng ID
customers = customers.drop_duplicates(
    subset=["customer_id"]
).reset_index(drop=True)

# Kiểm tra
print("Customers:")
print(customers.info())
print("\nNull:")
print(customers.isnull().sum())
print("\nDuplicate customer_id:",
      customers["customer_id"].duplicated().sum())

customers.head()

Customers:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121930 entries, 0 to 121929
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   customer_id          121930 non-null  Int64
 1   zip                  121930 non-null  Int64
 2   city                 121930 non-null  string
 3   signup_date          121930 non-null  datetime64[ns]
 4   gender               121930 non-null  string
 5   age_group            121930 non-null  string
 6   acquisition_channel  121930 non-null  string
dtypes: Int64(2), datetime64[ns](1), string(4)
memory usage: 6.7 MB
None

Null:
customer_id            0
zip                    0
city                   0
signup_date            0
gender                 0
age_group              0
acquisition_channel    0
dtype: int64

Duplicate customer_id: 0

,customer_id,zip,city,signup_date,gender,age_group,acquisition_channel
0,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media
1,2,15201,Hai Phong,2013-12-27,Female,45-54,email_campaign
2,3,15201,Hai Phong,2018-07-24,Female,18-24,organic_search
3,4,15201,Hai Phong,2017-11-29,Male,35-44,referral
4,5,15201,Hai Phong,2022-09-23,Male,55+,organic_search

In [19]:

# EPD - PRODUCT


product = product_epd_raw[
    [
        "product_id",
        "product_name",
        "category",
        "segment",
        "size",
        "color",
        "price",
        "cogs"
    ]
].copy()

# Chuẩn hóa text
for col in [
    "product_name",
    "category",
    "segment",
    "size",
    "color"
]:
    product[col] = (
        product[col]
        .astype("string")
        .str.strip()
    )

# Chuẩn hóa Product ID
product["product_id"] = pd.to_numeric(
    product["product_id"],
    errors="coerce"
).astype("Int64")

# Chuẩn hóa giá
product["price"] = pd.to_numeric(
    product["price"],
    errors="coerce"
)

# Chuẩn hóa giá vốn
product["cogs"] = pd.to_numeric(
    product["cogs"],
    errors="coerce"
)

# Xóa Product không có ID
product = product.dropna(
    subset=["product_id"]
)

# Xóa Product ID trùng
product = product.drop_duplicates(
    subset=["product_id"]
).reset_index(drop=True)

# Kiểm tra
print("Product:")
print(product.info())
print("\nNull:")
print(product.isnull().sum())
print("\nDuplicate product_id:",
      product["product_id"].duplicated().sum())

product.head()

Product:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 997 entries, 0 to 996
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    997 non-null    Int64
 1   product_name  997 non-null    string
 2   category      997 non-null    string
 3   segment       997 non-null    string
 4   size          997 non-null    string
 5   color         997 non-null    string
 6   price         996 non-null    float64
 7   cogs          997 non-null    float64
dtypes: Int64(1), float64(2), string(5)
memory usage: 63.4 KB
None

Null:
product_id      0
product_name    0
category        0
segment         0
size            0
color           0
price           1
cogs            0
dtype: int64

Duplicate product_id: 0

,product_id,product_name,category,segment,size,color,price,cogs
0,1,BambooCraft UC-21,Streetwear,Everyday,L,orange,19529.370000,16287.494580
1,2,MekongFit UC-07,Streetwear,Everyday,M,purple,4409.370000,3289.390020
2,3,SaigonFlex UC-59,Streetwear,Everyday,L,white,42.908735,24.500483
3,4,HanoiStreet UM-36,Streetwear,Balanced,S,orange,9109.170000,8653.711500
4,5,SaigonFlex UC-97,Streetwear,Everyday,S,orange,4844.700000,2618.075880

In [20]:

# EPROM - PROMOTION


promotion = promotion_eprom_raw[
    [
        "promo_id",
        "promo_name",
        "promo_type",
        "discount_value",
        "start_date",
        "end_date",
        "applicable_category",
        "promo_channel",
        "stackable_flag",
        "min_order_value"
    ]
].copy()

# Chuẩn hóa text
for col in [
    "promo_id",
    "promo_name",
    "promo_type",
    "applicable_category",
    "promo_channel"
]:
    promotion[col] = (
        promotion[col]
        .astype("string")
        .str.strip()
    )

# Chuẩn hóa số
promotion["discount_value"] = pd.to_numeric(
    promotion["discount_value"],
    errors="coerce"
)

promotion["stackable_flag"] = pd.to_numeric(
    promotion["stackable_flag"],
    errors="coerce"
).astype("Int64")

promotion["min_order_value"] = pd.to_numeric(
    promotion["min_order_value"],
    errors="coerce"
)

# Chuẩn hóa ngày
promotion["start_date"] = pd.to_datetime(
    promotion["start_date"],
    errors="coerce"
)

promotion["end_date"] = pd.to_datetime(
    promotion["end_date"],
    errors="coerce"
)

# Xóa Promotion không có ID
promotion = promotion.dropna(
    subset=["promo_id"]
)

# Xóa ID trùng
promotion = promotion.drop_duplicates(
    subset=["promo_id"]
).reset_index(drop=True)

# Kiểm tra
print("Promotion:")
print(promotion.info())
print("\nNull:")
print(promotion.isnull().sum())
print("\nDuplicate promo_id:",
      promotion["promo_id"].duplicated().sum())

promotion.head()

Promotion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   promo_id             1000 non-null   string
 1   promo_name           999 non-null    string
 2   promo_type           1000 non-null   string
 3   discount_value       998 non-null    float64
 4   start_date           1000 non-null   datetime64[ns]
 5   end_date             1000 non-null   datetime64[ns]
 6   applicable_category  217 non-null    string
 7   promo_channel        1000 non-null   string
 8   stackable_flag       1000 non-null   Int64
 9   min_order_value      1000 non-null   int64
dtypes: Int64(1), datetime64[ns](2), float64(1), int64(1), string(5)
memory usage: 79.2 KB
None

Null:
promo_id                 0
promo_name               1
promo_type               0
discount_value           2
start_date               0
end_date                 0
applicable_category    783
promo_channel            0
stackable_flag           0
min_order_value          0
dtype: int64

Duplicate promo_id: 0

,promo_id,promo_name,promo_type,discount_value,start_date,end_date,applicable_category,promo_channel,stackable_flag,min_order_value
0,PROMO-0039-0001,Fall Launch 2020,percentage,10.0,2020-08-30,2020-10-01,<NA>,all_channels,0,150000
1,PROMO-0029-0002,Fall Launch 2018,percentage,10.0,2018-08-30,2018-10-01,<NA>,email,0,0
2,PROMO-0015-0003,Urban Blowout 2015,fixed,50.0,2015-07-30,2015-09-02,Streetwear,online,0,200000
3,PROMO-0043-0004,Fall Launch 2021,percentage,10.0,2021-08-30,2021-10-02,<NA>,email,0,0
4,PROMO-0008-0005,Mid-Year Sale 2014,percentage,18.0,2014-06-23,2014-07-22,<NA>,social_media,0,0

In [22]:

# SHIPMENTS RAW CLEANING


ship_temp = shipments_realistic_raw.copy()

# Chuẩn hóa tên cột
ship_temp.columns = (
    ship_temp.columns
    .str.strip()
)

# Chuẩn hóa text
text_columns = [
    "shipper_id",
    "shipper_company",
    "shipper_vehicle",
    "working_shift",
    "shipper_name",
    "shipper_phone",
    "shipper_gender",
    "shipper_marital_status",
    "shipper_education",
    "city",
    "region",
    "district"
]

for col in text_columns:
    ship_temp[col] = (
        ship_temp[col]
        .astype("string")
        .str.strip()
    )

# Chuẩn hóa ID
ship_temp["order_id"] = pd.to_numeric(
    ship_temp["order_id"],
    errors="coerce"
).astype("Int64")

# Chuẩn hóa số
numeric_columns = [
    "shipping_fee",
    "shipper_experience_years",
    "shipper_rating",
    "delivery_success_rate",
    "average_delivery_time",
    "shipper_age"
]

for col in numeric_columns:
    ship_temp[col] = pd.to_numeric(
        ship_temp[col],
        errors="coerce"
    )

# Chuẩn hóa ngày
ship_temp["ship_date"] = pd.to_datetime(
    ship_temp["ship_date"],
    errors="coerce"
)

ship_temp["delivery_date"] = pd.to_datetime(
    ship_temp["delivery_date"],
    errors="coerce"
)

ship_temp["join_date"] = pd.to_datetime(
    ship_temp["join_date"],
    errors="coerce"
)

In [23]:

# SHIPPERS


shippers = ship_temp[
    [
        "shipper_id",
        "shipper_company",
        "shipper_vehicle",
        "shipper_experience_years",
        "shipper_rating",
        "delivery_success_rate",
        "average_delivery_time",
        "working_shift",
        "join_date",
        "shipper_name",
        "shipper_phone",
        "shipper_gender",
        "shipper_age",
        "shipper_marital_status",
        "shipper_education",
        "city",
        "region",
        "district"
    ]
].copy()

# Xóa Shipper ID thiếu
shippers = shippers.dropna(
    subset=["shipper_id"]
)

# Xóa Shipper trùng
shippers = shippers.drop_duplicates(
    subset=["shipper_id"]
).reset_index(drop=True)

shippers.head()

,shipper_id,shipper_company,shipper_vehicle,shipper_experience_years,shipper_rating,delivery_success_rate,average_delivery_time,working_shift,join_date,shipper_name,shipper_phone,shipper_gender,shipper_age,shipper_marital_status,shipper_education,city,region,district
0,SHP00001,Viettel Post,Truck,7,5.0,99.0,61,Evening,2026-03-17,Bùi Văn Long,991476209,Male,27,Married,Bachelor,Phan Rang-Thap Cham,Central,District #25
1,SHP00002,J&T Express,Van,2,4.9,98.4,72,Afternoon,2025-01-29,Trần Anh Khánh,959297982,Male,41,Married,Bachelor,Phan Thiet,Central,District #29
2,SHP00003,GHN,Motorbike,10,4.8,95.1,53,Evening,2019-11-13,Hoàng Thị Khánh,927142576,Male,30,Single,High School,Long Xuyen,West,District #34
3,SHP00004,Viettel Post,Truck,8,5.0,96.3,53,Evening,2025-12-22,Trần Đức Vy,971617475,Female,42,Married,College,Kon Tum,Central,District #27
4,SHP00005,BEST Express,Truck,10,4.6,95.7,62,Morning,2019-12-19,Trần Minh Cường,979196342,Male,31,Married,College,Da Nang,Central,District #23

In [24]:

# ADD ZIP TO SHIPPERS


geo_map = geography[
    [
        "zip",
        "city",
        "region",
        "district"
    ]
].copy()

# Tạo bản sao để chuẩn hóa cho việc merge
geo_map["city"] = (
    geo_map["city"]
    .astype("string")
    .str.strip()
    .str.lower()
)

geo_map["region"] = (
    geo_map["region"]
    .astype("string")
    .str.strip()
    .str.lower()
)

geo_map["district"] = (
    geo_map["district"]
    .astype("string")
    .str.strip()
    .str.lower()
)

shippers["city"] = (
    shippers["city"]
    .astype("string")
    .str.strip()
    .str.lower()
)

shippers["region"] = (
    shippers["region"]
    .astype("string")
    .str.strip()
    .str.lower()
)

shippers["district"] = (
    shippers["district"]
    .astype("string")
    .str.strip()
    .str.lower()
)

geo_map = geo_map.drop_duplicates(
    subset=["city", "region", "district"]
)

shippers = shippers.merge(
    geo_map,
    on=["city", "region", "district"],
    how="left"
)

shippers.head()

,shipper_id,shipper_company,shipper_vehicle,shipper_experience_years,shipper_rating,delivery_success_rate,average_delivery_time,working_shift,join_date,shipper_name,shipper_phone,shipper_gender,shipper_age,shipper_marital_status,shipper_education,city,region,district,zip
0,SHP00001,Viettel Post,Truck,7,5.0,99.0,61,Evening,2026-03-17,Bùi Văn Long,991476209,Male,27,Married,Bachelor,phan rang-thap cham,central,district #25,38006
1,SHP00002,J&T Express,Van,2,4.9,98.4,72,Afternoon,2025-01-29,Trần Anh Khánh,959297982,Male,41,Married,Bachelor,phan thiet,central,district #29,63112
2,SHP00003,GHN,Motorbike,10,4.8,95.1,53,Evening,2019-11-13,Hoàng Thị Khánh,927142576,Male,30,Single,High School,long xuyen,west,district #34,97005
3,SHP00004,Viettel Post,Truck,8,5.0,96.3,53,Evening,2025-12-22,Trần Đức Vy,971617475,Female,42,Married,College,kon tum,central,district #27,55919
4,SHP00005,BEST Express,Truck,10,4.6,95.7,62,Morning,2019-12-19,Trần Minh Cường,979196342,Male,31,Married,College,da nang,central,district #23,75102

In [25]:
print(
    "Số Shipper không tìm được ZIP:",
    shippers["zip"].isna().sum()
)

Số Shipper không tìm được ZIP: 0

In [26]:

# SHIPMENTS


shipments = ship_temp[
    [
        "order_id",
        "shipper_id",
        "ship_date",
        "delivery_date",
        "shipping_fee"
    ]
].copy()

# Xóa Order không có ID
shipments = shipments.dropna(
    subset=["order_id"]
)

# Xóa Order bị trùng
shipments = shipments.drop_duplicates(
    subset=["order_id"]
).reset_index(drop=True)

shipments.head()

   order_id shipper_id  ship_date delivery_date  shipping_fee
0         1   SHP00001 2012-07-07    2012-07-11          1.37
1         2   SHP00002 2012-07-06    2012-07-10          2.60
2         3   SHP00003 2012-07-04    2012-07-07          2.38
3         4   SHP00004 2012-07-05    2012-07-11          2.49
4         6   SHP00005 2012-07-09    2012-07-16         25.79

In [27]:

# CHECK SHIPPER ID


invalid_shipper = shipments[
    ~shipments["shipper_id"].isin(
        shippers["shipper_id"]
    )
]

print(
    "Số Shipment có shipper_id không tồn tại:",
    len(invalid_shipper)
)

Số Shipment có shipper_id không tồn tại: 0

In [28]:
# TF

tf = tf_raw[
    [
        "date",
        "sessions",
        "unique_visitors",
        "page_views",
        "bounce_rate",
        "avg_session_duration_sec",
        "traffic_source"
    ]
].copy()

# Chuẩn hóa ngày
tf["date"] = pd.to_datetime(
    tf["date"],
    errors="coerce"
)

# Chuẩn hóa số
numeric_columns = [
    "sessions",
    "unique_visitors",
    "page_views",
    "bounce_rate",
    "avg_session_duration_sec"
]

for col in numeric_columns:
    tf[col] = pd.to_numeric(
        tf[col],
        errors="coerce"
    )

# Chuẩn hóa traffic source
tf["traffic_source"] = (
    tf["traffic_source"]
    .astype("string")
    .str.strip()
)

# Xóa ngày thiếu
tf = tf.dropna(
    subset=["date"]
).reset_index(drop=True)

tf.head()

,date,sessions,unique_visitors,page_views,bounce_rate,avg_session_duration_sec,traffic_source
0,2013-10-26,12422.0,8842.0,45914,0.00452,197.1,organic_search Variant 0001
1,2019-02-15,26260.0,19148.0,97929,0.00568,116.5,paid_search Variant 0002
2,2019-01-12,14383.0,11480.0,57737,0.00466,170.6,email_campaign Variant 0003
3,2017-09-30,22021.0,16969.0,95903,0.00344,111.8,paid_search Variant 0004
4,2021-08-12,38269.0,29771.0,208637,0.00442,210.7,paid_search Variant 0005

In [29]:
tf["traffic_source"] = (
    tf["traffic_source"]
    .replace("", pd.NA)
)

In [30]:
# WEB TRAFFIC


web_traffic = web_traffic_raw[
    [
        "date",
        "sessions",
        "unique_visitors",
        "page_views",
        "bounce_rate",
        "avg_session_duration_sec",
        "traffic_source"
    ]
].copy()

# Chuẩn hóa ngày
web_traffic["date"] = pd.to_datetime(
    web_traffic["date"],
    errors="coerce"
)

# Chuẩn hóa số
numeric_columns = [
    "sessions",
    "unique_visitors",
    "page_views",
    "bounce_rate",
    "avg_session_duration_sec"
]

for col in numeric_columns:
    web_traffic[col] = pd.to_numeric(
        web_traffic[col],
        errors="coerce"
    )

# Chuẩn hóa text
web_traffic["traffic_source"] = (
    web_traffic["traffic_source"]
    .astype("string")
    .str.strip()
)

# Chuyển chuỗi rỗng thành NA
web_traffic["traffic_source"] = (
    web_traffic["traffic_source"]
    .replace("", pd.NA)
)

# Xóa ngày thiếu
web_traffic = web_traffic.dropna(
    subset=["date"]
).reset_index(drop=True)

web_traffic.head()

,date,sessions,unique_visitors,page_views,bounce_rate,avg_session_duration_sec,traffic_source
0,2013-01-01,9760,7253,39093,0.00514,102.9,organic_search
1,2013-01-02,10456,8151,47611,0.00406,120.5,organic_search
2,2013-01-03,10076,7458,36963,0.00401,263.6,direct
3,2013-01-04,9973,8063,53078,0.00562,151.8,direct
4,2013-01-05,10223,7882,36790,0.00525,168.6,referral

In [31]:

# ktra toàn bộ silver


silver_tables = {
    "customers": customers,
    "geography": geography,
    "product": product,
    "promotion": promotion,
    "shippers": shippers,
    "shipments": shipments,
    "tf": tf,
    "web_traffic": web_traffic
}

for name, df in silver_tables.items():

    print("=" * 60)
    print(name.upper())

    print("Rows:", len(df))
    print("Columns:", len(df.columns))

    print("\nNull values:")
    print(df.isnull().sum())

    print("\nDuplicate rows:", df.duplicated().sum())

============================================================
CUSTOMERS
Rows: 121930
Columns: 7

Null values:
customer_id            0
zip                    0
city                   0
signup_date            0
gender                 0
age_group              0
acquisition_channel    0
dtype: int64

Duplicate rows: 0
============================================================
GEOGRAPHY
Rows: 39948
Columns: 4

Null values:
zip         0
city        0
region      0
district    0
dtype: int64

Duplicate rows: 0
============================================================
PRODUCT
Rows: 997
Columns: 8

Null values:
product_id      0
product_name    0
category        0
segment         0
size            0
color           0
price           1
cogs            0
dtype: int64

Duplicate rows: 0
============================================================
PROMOTION
Rows: 1000
Columns: 10

Null values:
promo_id                 0
promo_name               1
promo_type               0
discount_value           2
start_date               0
end_date                 0
applicable_category    783
promo_channel            0
stackable_flag           0
min_order_value          0
dtype: int64

Duplicate rows: 0
============================================================
SHIPPERS
Rows: 80
Columns: 19

Null values:
shipper_id                  0
shipper_company             0
shipper_vehicle             0
shipper_experience_years    0
shipper_rating              0
delivery_success_rate       0
average_delivery_time       0
working_shift               0
join_date                   0
shipper_name                0
shipper_phone               0
shipper_gender              0
shipper_age                 0
shipper_marital_status      0
shipper_education           0
city                        0
region                      0
district                    0
zip                         0
dtype: int64

Duplicate rows: 0
============================================================
SHIPMENTS
Rows: 566067
Columns: 5

Null values:
order_id         0
shipper_id       0
ship_date        0
delivery_date    0
shipping_fee     0
dtype: int64

Duplicate rows: 0
============================================================
TF
Rows: 998
Columns: 7

Null values:
date                        0
sessions                    2
unique_visitors             1
page_views                  0
bounce_rate                 0
avg_session_duration_sec    0
traffic_source              1
dtype: int64

Duplicate rows: 0
============================================================
WEB_TRAFFIC
Rows: 3652
Columns: 7

Null values:
date                        0
sessions                    0
unique_visitors             0
page_views                  0
bounce_rate                 0
avg_session_duration_sec    0
traffic_source              0
dtype: int64

Duplicate rows: 0